version: '3.3'
name: poc-quartz
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    hostname: postgres.docker.internal
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 172.20.0.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Configs/PostgreSQL/InitialScripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: POC_QRTZ
      POSTGRES_USER: pocadmin
      POSTGRES_PASSWORD: qwert1234

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on: [postgres]
    hostname: pgadmin.docker.internal
    ports:
      - "5050:80"
    networks:
      default:
        ipv4_address: 172.20.0.3
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@poc.com
      PGADMIN_DEFAULT_PASSWORD: qwert1234

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1

volumes:
  postgres-data:
  pgadmin-data: